
[package]
name = "leetcode"
version = "0.1.0"
edition = "2021"

[package.metadata.clippy]
allow = ["unused", "dead_code"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
regex = "1.9.5"
rand = { version = "0.8.5", features = [] }
